/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityLogIndexRouteImport } from './routes/activity-log.index'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CreditNotesIndexRouteImport } from './routes/credit-notes.index'
import { Route as ExpensesIndexRouteImport } from './routes/expenses.index'
import { Route as HoursIndexRouteImport } from './routes/hours.index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as PayrollIndexRouteImport } from './routes/payroll.index'
import { Route as RecycleBinIndexRouteImport } from './routes/recycle-bin.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as SalaryIndexRouteImport } from './routes/salary.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StatementsIndexRouteImport } from './routes/statements.index'
import { Route as SubcontractingIndexRouteImport } from './routes/subcontracting.index'
import { Route as TimesheetsIndexRouteImport } from './routes/timesheets.index'
import { Route as UsersIndexRouteImport } from './routes/users.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityLogIndexRoute = ActivityLogIndexRouteImport.update({
  id: '/activity-log/',
  path: '/activity-log/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditNotesIndexRoute = CreditNotesIndexRouteImport.update({
  id: '/credit-notes/',
  path: '/credit-notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoursIndexRoute = HoursIndexRouteImport.update({
  id: '/hours/',
  path: '/hours/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollIndexRoute = PayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecycleBinIndexRoute = RecycleBinIndexRouteImport.update({
  id: '/recycle-bin/',
  path: '/recycle-bin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryIndexRoute = SalaryIndexRouteImport.update({
  id: '/salary/',
  path: '/salary/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementsIndexRoute = StatementsIndexRouteImport.update({
  id: '/statements/',
  path: '/statements/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubcontractingIndexRoute = SubcontractingIndexRouteImport.update({
  id: '/subcontracting/',
  path: '/subcontracting/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesheetsIndexRoute = TimesheetsIndexRouteImport.update({
  id: '/timesheets/',
  path: '/timesheets/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/activity-log/': typeof ActivityLogIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/credit-notes/': typeof CreditNotesIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/hours/': typeof HoursIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/recycle-bin/': typeof RecycleBinIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/salary/': typeof SalaryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/statements/': typeof StatementsIndexRoute
  '/subcontracting/': typeof SubcontractingIndexRoute
  '/timesheets/': typeof TimesheetsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/activity-log': typeof ActivityLogIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/credit-notes': typeof CreditNotesIndexRoute
  '/expenses': typeof ExpensesIndexRoute
  '/hours': typeof HoursIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/payroll': typeof PayrollIndexRoute
  '/recycle-bin': typeof RecycleBinIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/salary': typeof SalaryIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/statements': typeof StatementsIndexRoute
  '/subcontracting': typeof SubcontractingIndexRoute
  '/timesheets': typeof TimesheetsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/activity-log/': typeof ActivityLogIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/credit-notes/': typeof CreditNotesIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/hours/': typeof HoursIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/recycle-bin/': typeof RecycleBinIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/salary/': typeof SalaryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/statements/': typeof StatementsIndexRoute
  '/subcontracting/': typeof SubcontractingIndexRoute
  '/timesheets/': typeof TimesheetsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients/$clientId'
    | '/activity-log/'
    | '/clients/'
    | '/companies/'
    | '/credit-notes/'
    | '/expenses/'
    | '/hours/'
    | '/invoices/'
    | '/payments/'
    | '/payroll/'
    | '/recycle-bin/'
    | '/reports/'
    | '/salary/'
    | '/settings/'
    | '/staff/'
    | '/statements/'
    | '/subcontracting/'
    | '/timesheets/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients/$clientId'
    | '/activity-log'
    | '/clients'
    | '/companies'
    | '/credit-notes'
    | '/expenses'
    | '/hours'
    | '/invoices'
    | '/payments'
    | '/payroll'
    | '/recycle-bin'
    | '/reports'
    | '/salary'
    | '/settings'
    | '/staff'
    | '/statements'
    | '/subcontracting'
    | '/timesheets'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/clients/$clientId'
    | '/activity-log/'
    | '/clients/'
    | '/companies/'
    | '/credit-notes/'
    | '/expenses/'
    | '/hours/'
    | '/invoices/'
    | '/payments/'
    | '/payroll/'
    | '/recycle-bin/'
    | '/reports/'
    | '/salary/'
    | '/settings/'
    | '/staff/'
    | '/statements/'
    | '/subcontracting/'
    | '/timesheets/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ActivityLogIndexRoute: typeof ActivityLogIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  CreditNotesIndexRoute: typeof CreditNotesIndexRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
  HoursIndexRoute: typeof HoursIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  PayrollIndexRoute: typeof PayrollIndexRoute
  RecycleBinIndexRoute: typeof RecycleBinIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SalaryIndexRoute: typeof SalaryIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StatementsIndexRoute: typeof StatementsIndexRoute
  SubcontractingIndexRoute: typeof SubcontractingIndexRoute
  TimesheetsIndexRoute: typeof TimesheetsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-log/': {
      id: '/activity-log/'
      path: '/activity-log'
      fullPath: '/activity-log/'
      preLoaderRoute: typeof ActivityLogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-notes/': {
      id: '/credit-notes/'
      path: '/credit-notes'
      fullPath: '/credit-notes/'
      preLoaderRoute: typeof CreditNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hours/': {
      id: '/hours/'
      path: '/hours'
      fullPath: '/hours/'
      preLoaderRoute: typeof HoursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll/': {
      id: '/payroll/'
      path: '/payroll'
      fullPath: '/payroll/'
      preLoaderRoute: typeof PayrollIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycle-bin/': {
      id: '/recycle-bin/'
      path: '/recycle-bin'
      fullPath: '/recycle-bin/'
      preLoaderRoute: typeof RecycleBinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary/': {
      id: '/salary/'
      path: '/salary'
      fullPath: '/salary/'
      preLoaderRoute: typeof SalaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statements/': {
      id: '/statements/'
      path: '/statements'
      fullPath: '/statements/'
      preLoaderRoute: typeof StatementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subcontracting/': {
      id: '/subcontracting/'
      path: '/subcontracting'
      fullPath: '/subcontracting/'
      preLoaderRoute: typeof SubcontractingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timesheets/': {
      id: '/timesheets/'
      path: '/timesheets'
      fullPath: '/timesheets/'
      preLoaderRoute: typeof TimesheetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ActivityLogIndexRoute: ActivityLogIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  CreditNotesIndexRoute: CreditNotesIndexRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
  HoursIndexRoute: HoursIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  PayrollIndexRoute: PayrollIndexRoute,
  RecycleBinIndexRoute: RecycleBinIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SalaryIndexRoute: SalaryIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  StatementsIndexRoute: StatementsIndexRoute,
  SubcontractingIndexRoute: SubcontractingIndexRoute,
  TimesheetsIndexRoute: TimesheetsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
